# shellcheck shell=sh
OM_TARGET=$(terraform output -state="${STATE_FILE}" ops_manager_dns)
export OM_TARGET
export OM_USERNAME="${OPSMAN_USER}"
export OM_PASSWORD="${OPSMAN_PASSWORD}"
export OM_DECRYPTION_PASSPHRASE="${OPSMAN_DECRYPTION_PASSPHRASE}"
export OM_SKIP_SSL_VALIDATION="${OPSMAN_SKIP_SSL_VALIDATION}"